### ISSUE TITLE
Api reference documentation link is broken/outdated

### ISSUE THREAD

**Issue by jul-reb** [walidshaari/Kubernetes-Certified-Administrator#21]
Pull request will follow.

**Comment by jul-reb** [comment]
https://github.com/walidshaari/Kubernetes-Certified-Administrator/pull/22
By the way, thanks for this handy dandy repo. :)

**Comment by walidshaari** [comment]
thank you @jul-reb 
I wonder if there is a way to always reference the latest APIs,  maybe script it

**Comment by jul-reb** [comment]
Jinja templating the guide perhaps, though it would need to be rendered instead of being used as plaintext.
