### ISSUE TITLE
Is Sonobuoy the official exam-tested way to run end to end tests?

### ISSUE THREAD

**Issue by matthewfischer** [walidshaari/Kubernetes-Certified-Administrator#4]
I think it's odd that Heptio's Sonobuoy (which is probably a great tool) would be on the official CNCF exam as the way to do end-to-end testing. Would love to hear thoughts on this or alternatives.

**Comment by walidshaari** [comment]
just simple validation, if you have deployed a simple pod, is the container
pulled and pod running as it should be? same for other resources. Validate
that the desired state if your configuration of the resource is achieved,
same for replicasets, deployments, daemonsets,  ...etc.

if it is installation/troubleshooting, what does the logs tell you?
validate using
simple commands, are required services enabled and running?  required
system/app pods running, correct namespaces, basic commands like `kubectl
get componentstatuses`, is etcd functioning correctly.

Sonobuoy is an overkill, it is meant to check the whole kubernetes cluster
distribution, isn't it?  it is an over kill in terms of time and resources.

**Comment by walidshaari** [comment]
I do not believe it is. just simple validation, the term end-2-end test does not mean to run the full cluster test functionality, there is no time, and one will exhaust the resources given.

if you have deployed a simple pod, is the container pulled and pod running as it should be? same for other resources. Validate that the desired state if your configuration of the resource is achieved, same for replicasets, deployments, daemonsets,  ...etc.

if it is installation/troubleshooting, what do the logs tell you?
validate using simple commands, are required services enabled and running?  required system/app pods running, correct namespaces, basic commands like 

```
kubectl get componentstatuses 
kubectl  get pods -o wide --show-labels --all-namespaces
kubectl  get deployment -o wide --show-labels --all-namespaces
kubectl describe pods <PODID>

**Comment by matthewfischer** [comment]
So then I would vote to put that content back. The PR before mine removed it all and basically said "run Sonobuoy". Where Sonobuoy is great for the real world, as you said, it's overkill for the exam.

**Comment by walidshaari** [comment]
@matthewfischer I agree completely,  the previous PR was more than that though, create a PR and will remove it immediately.  what would you put instead for e-2-e testing?  I also do not know the current release of the exam, someone told me over LinkedIn 1.9. however, could not verify it?

**Comment by matthewfischer** [comment]
It is indeed 1.9 based on the current exam guide. I'll work on a PR for this tomorrow. I think having your notes plus a link to e2e would be enough. I don't think you'll need to run e2e during the test but should know about it.

**Comment by walidshaari** [comment]
I am attending FOSDEM, and cfgmgmtcamp this week, when I am back, I will try to review what changes are needed. It was initially written with 1.6 in mind. k8s moves quickly, and LF is doing a great job keeping exam fresh

**Comment by matthewfischer** [comment]
Have a great time, I have a bunch of friends there. I will be sending some PRs over the weekend. No rush!
