### ISSUE TITLE
Working with images securely missing links

### ISSUE THREAD

**Issue by matthewfischer** [walidshaari/Kubernetes-Certified-Administrator#9]
Would recommend:

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://kubernetes.io/docs/admin/admission-controllers/

Per discussion on kubernauts slack

**Comment by matthewfischer** [comment]
OTOH security context is already used and admission controllers are not image specific, so open to other ideas

**Comment by matthewfischer** [comment]
I'm now thinking that it means:

https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry

and

https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod

**Comment by matthewfischer** [comment]
Could also mean: don't use latest and validate the SHAs: 

https://kubernetes.io/docs/concepts/configuration/overview/#container-images

**Comment by walidshaari** [comment]
I am not sure, I did not pay attention to slack, what objective is this?

**Comment by matthewfischer** [comment]
"Working with images securely" is the section, under Security

**Comment by walidshaari** [comment]
I believe you are right when thinking private registry with enabled SSL. admission controllers are new to me, however, seems probable, but, security-context is more with pods and containers, not images.  I have to admit the exam seems to have evolved.

**Comment by walidshaari** [comment]
closing
